Repository OpenKMIP/PyKMIP, pull requests merged in 2019-03, with the labels that each got.

#499 Add utilities for converting TemplateAttributes and Attributes
  kmip/core/enums.py
  kmip/core/objects.py
  kmip/tests/unit/core/objects/test_objects.py
  kmip/tests/unit/core/test_enums.py
Labels: feature

#500 Update the Create payloads to support KMIP 2.0
  kmip/core/messages/payloads/create.py
  kmip/tests/unit/core/messages/payloads/test_create.py
Labels: feature

#498 Move TLS server handshake down to connection thread
  kmip/services/server/server.py
  kmip/services/server/session.py
Labels: TLS/SSL, performance, server

#501 Update the Register payloads
  kmip/core/messages/payloads/register.py
  kmip/demos/units/register.py
  kmip/pie/client.py
  kmip/services/kmip_client.py
  kmip/services/server/engine.py
  kmip/tests/integration/services/test_integration.py
  kmip/tests/integration/services/test_kmip_client.py
  kmip/tests/unit/core/messages/payloads/test_register.py
  kmip/tests/unit/core/messages/test_messages.py
  kmip/tests/unit/pie/test_client.py
  kmip/tests/unit/services/server/test_engine.py
Labels: client, feature, testing

#502 Update the Register payloads to support KMIP 2.0
  kmip/core/messages/payloads/register.py
  kmip/tests/unit/core/messages/payloads/test_register.py
Labels: feature

#503 Add bit mask enumeration utilities
  kmip/core/enums.py
  kmip/tests/unit/core/test_enums.py
Labels: feature

#504 Update the Locate payloads
  kmip/core/messages/payloads/locate.py
  kmip/pie/client.py
  kmip/services/kmip_client.py
  kmip/services/server/engine.py
  kmip/tests/unit/core/messages/payloads/test_locate.py
  kmip/tests/unit/core/messages/test_messages.py
  kmip/tests/unit/pie/test_client.py
  kmip/tests/unit/services/server/test_engine.py
Labels: client, feature, testing

#505 Update the Locate payloads to support KMIP 2.0
  kmip/core/messages/payloads/locate.py
  kmip/tests/unit/core/messages/payloads/test_locate.py
Labels: feature

#506 Update the CreateKeyPair payloads
  kmip/core/messages/payloads/create_key_pair.py
  kmip/core/messages/payloads/rekey_key_pair.py
  kmip/demos/pie/create_key_pair.py
  kmip/demos/units/create_key_pair.py
  kmip/pie/client.py
  kmip/services/kmip_client.py
  kmip/services/server/engine.py
  kmip/tests/integration/services/test_integration.py
  kmip/tests/unit/core/messages/payloads/test_create_key_pair.py
  kmip/tests/unit/core/messages/payloads/test_rekey_key_pair.py
  kmip/tests/unit/pie/test_client.py
  kmip/tests/unit/services/server/test_engine.py
Labels: client, feature, testing

#508 Update the CreateKeyPair payloads to support KMIP 2.0
  kmip/core/messages/payloads/create_key_pair.py
  kmip/tests/unit/core/messages/payloads/test_create_key_pair.py
Labels: feature

#510 Move the KMIPProtocol from server to services
  kmip/services/kmip_client.py
  kmip/services/kmip_protocol.py
  kmip/tests/unit/services/test_kmip_protocol.py
Labels: client, potential bug

#513 Update the DeriveKey payloads to support KMIP 2.0
  kmip/core/messages/payloads/derive_key.py
  kmip/tests/unit/core/messages/payloads/test_derive_key.py
Labels: feature

#514 Add the AttributeReference structure
  kmip/core/objects.py
  kmip/tests/unit/core/objects/test_objects.py
Labels: feature

#515 Implement simple CLI for GET_ATTRIBUTES operation
  kmip/demos/pie/get_attributes.py
  kmip/demos/utils.py
Labels: demos

#516 Update the GetAttributes payloads
  kmip/core/messages/payloads/get_attributes.py
  kmip/tests/unit/core/messages/payloads/test_get_attributes.py
Labels: feature

#517 Update the GetAttributes payloads to support KMIP 2.0
  kmip/core/messages/payloads/get_attributes.py
  kmip/tests/unit/core/messages/payloads/test_get_attributes.py
Labels: feature
